### ISSUE TITLE
ExtendedBlock cause onGround failed

### ISSUE THREAD

**Issue by UnEnanoMas** [Blackjack200/Lunar#5]
![image](https://user-images.githubusercontent.com/63286108/114734216-4f609a00-9d44-11eb-9179-adcf8fd71d49.png)

When you try to climb scaffold blocks by jumping, Lunar detects FlyB and won't let you climb

Scaffold added with the plugin: https://poggit.pmmp.io/p/ExtendedBlocks/1.1.1
Lunar: Dev 29
PMMP: 3.19.0
OS: Linux
PHP: 7.4
Minecraft: 1.16.220

**Comment by Blackjack200** [comment]
https://github.com/JavierLeon9966/ExtendedBlocks/issues/39

**Comment by Blackjack200** [comment]
according to https://github.com/JavierLeon9966/ExtendedBlocks/issues/39, 
you should add this block to Transparent
